### ISSUE TITLE
The Meteoriks need you! 

### ISSUE THREAD

**Issue by dojoe** [xjorma/HoloGrail#1]
Hey, congratulations first of all on your nomination in the New Talent category of the Meteoriks Awards :)
For the awards show on Good Friday we're looking for short videos from our nominees to add a personal touch to the event. You should have received an email from leia at scene dot org with details.
We haven't heard back from you yet so we're trying other channels now ;) Please respond ASAP, it would be really great to have you on screen :)
All the best,
  dojoe

**Comment by xjorma** [comment]
Hello,

I suck doing this kind of video. But I uploaded something on the ftp:

HoloSapiens_HoloGrail_NewTalent.MOV

David.

**Comment by dojoe** [comment]
Hi David,

Thank you, much appreciated! It may feel awkward making the video, but you'll see how it makes the show a lot more personal if everyone says hi :)

All the best,
  Joachim / dojoe
